### ISSUE TITLE
Error while song request

### ISSUE THREAD

**Issue by oded106e** [reger-men/Alexa_YouTube#9] opened 2018-12-02 22:47 UTC
Hey,
I received this error in the lambda:
2018-12-02T22:36:52.744Z b1e905a0-f682-11e8-b5c8-f71fdb07a242 SyntaxError: Unexpected token < in JSON at position 0
at Object.parse (native)
at Request._callback (/var/task/index.js:225:32)
at Request.self.callback (/var/task/node_modules/request/request.js:186:22)
at emitTwo (events.js:106:13)
at Request.emit (events.js:191:7)
at Request.<anonymous> (/var/task/node_modules/request/request.js:1163:10)
at emitOne (events.js:96:13)
at Request.emit (events.js:188:7)
at IncomingMessage.<anonymous> (/var/task/node_modules/request/request.js:1085:12)
at IncomingMessage.g (events.js:292:16)
at emitNone (events.js:91:20)
at IncomingMessage.emit (events.js:185:7)
at endReadableNT (_stream_readable.js:974:12)
at _combinedTickCallback (internal/process/next_tick.js:80:11)
at process._tickDomainCallback (internal/process/next_tick.js:128:9) 

and the song not playing.
this is occurs only in specific songs.
I tried to reinstall - without successful 
Thanks!

**Comment by reger-men** [comment] 2018-12-02 23:51
Could you please check one more time and let me know how its look.

**Comment by oded106e** [comment] 2018-12-03 07:15
Hey,
now its work fine!
Thanks!

But now there is another problem :)
The time between the song request and its actual playlist is about one minute..
there is any option to make it shorter?
(in the older version, before a week, it work)
Thanks Again!

![capture](https://user-images.githubusercontent.com/45544837/49361144-ef717780-f6e3-11e8-8d9a-6f2e15fbd81f.PNG)

**Comment by reger-men** [comment] 2018-12-04 04:31
Can you confirm now that the song is playing within 10s?

**Comment by oded106e** [comment] 2018-12-04 19:08
Hey,
Now its respond within 10s.
but after alexa says: Im now playing "bla bla" I need to say "Alexa ask youtube to play" and then the song start. 
Many Thanks!

**Comment by reger-men** [comment] 2018-12-04 19:51
I suppose you use echo dot. If yes, than maybe the problem is in the Echo device driver.
You can try to call this skills over your mobile app Alexa and let me know whether the same case occurs. Thanks.

**Comment by oded106e** [comment] 2018-12-05 01:00
Yes, on the mobile app it's work good.
There is something that I can do (from my side) to slove this?
And how this is work with the older version? The driver is changed?

Thanks!

**Comment by reger-men** [comment] 2019-01-07 12:03
Could you please try one more time and let me know if it wotk now and on which device. Thanks.

**Comment by oded106e** [comment] 2019-01-07 19:39
Yes, i think its perfect! 

Now I have enhacment request 😀
If i want to use my google account with my playlists - can I do that? 

Thanks a lot!

**Comment by reger-men** [comment] 2019-01-08 09:03
Sure. There are various way to do that. For npm you can use [googleapis](https://www.npmjs.com/package/googleapis).

I close this issue since the original problem was solved here. Feel free to reopen it if this issue still exists.

**Closed as completed by reger-men** 2019-01-08 09:03 UTC
